### ISSUE TITLE
possible to return variables?

### ISSUE THREAD

**Issue by pixelpaulaus** [bainternet/PHP-Hooks#18]
is it possible to return a variable in one of the hook functions that run for all the rest of the functions on the same hook?

**Comment by bainternet** [comment]
?? what ??

**Comment by fef06** [comment]
is it possible to return a value instead of an echo ?

**Comment by BassemN** [comment]
Can you please write a sample of code you are using so we can help?

**Comment by Akamaozu** [comment]
@bainternet @BassemN I think he's talking about how WordPress filters behave.

@pixelpaulaus Do you mean something like this?

<pre>
<code>
include_once('php-hooks.php');
global $hooks;
$hooks->add_action('print_user_name','capitalize_string');
$hooks->add_action('print_user_name','color_string');
function capitalize_string( string ){
   return strtoupper(string );
}
function color_string( string ){
   return '&lt;span class="orange-text"&gt;' . string . '&lt;/span&gt;';
}
$hooks->do_action('print_user_name', 'pixelpaulaus'); 
// returns &lt;span class='orange-text'&gt;PIXELPAULAUS&lt;/span&gt;
</code>
</pre>

**Comment by abdo-host** [comment]
what about add action in class like this

```
$hooks = new Hooks();

function add_action($action, $function) {
    global $hooks;
    $hooks->add_action($action, $function);
}

class C_Knowledges {


    public function __construct() {
        add_action('ajax', array($this, 'add_knowledges'));
    }

    public function add_knowledges() {
        echo 'ddddddddddddddd';
    }

}

```

**Comment by bainternet** [comment]
What about it?

It should work fine
